### ISSUE TITLE
[Panpress] fail to build md file when a js code sample with a complex template string is included

### ISSUE THREAD

**Issue by noelmace** [fullwebdev/fullwebdev#32]
# Panpress - 🐞 Bug report

## Description

This bug occurs at:

- [x] build time (cli)
- [ ] run time (starter, etc...)

## Actual Behavior

When a complex code sample with some template strings is used, Panpress doesn't escape the characters correctly. When serving the file, it results to a 404, and the entry isn't added to the menu.

## Possible Fix

Code samples aren't escaped correctly for some complex case in :
https://github.com/fullwebdev/fullwebdev/blob/panpress%40v0.3.0-beta.5/packages/panpress/cli/src/build/html-to-js.js#L61-L64

## Steps to Reproduce

See website (from a private file):

```
path: /en/02-fundamentals/02-materials/3-web-components/2-custom-elements
[routes] callback failed for /en/02-fundamentals/02-materials/3-web-components/2-custom-elements
Error: 404 View
    at getTitle (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/generate-data.js:43:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async recurse (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/dir-to-routes.js:65:22)
    at async recurse (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/dir-to-routes.js:35:25)
    at async recurse (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/dir-to-routes.js:35:25)
    at async recurse (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/dir-to-routes.js:35:25)
    at async recurse (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/dir-to-routes.js:35:25)
    at async dirToRoutes (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/dir-to-routes.js:87:19)
    at async module.exports.generateData (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/generate-data.js:138:18)
    at async generateAll (/home/runner/work/fullwebdev/fullwebdev/packages/panpress/cli/src/generate/index.js:17:31)
```

**Comment by noelmace** [comment]
Will be solved by Daucus.
