### ISSUE TITLE
[CI] fix lhci report upload to server

### ISSUE THREAD

**Issue by noelmace** [fullwebdev/fullwebdev#46]
# CI

## Description

The `deploy website` gh action gives the following error:

```
All results processed!

Error: Unexpected status code 500
  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>

    at ApiClient._convertFetchResponseToReturnValue (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/@lhci/cli/node_modules/@lhci/utils/src/api-client.js:78:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runLHCITarget (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/@lhci/cli/src/upload/upload.js:398:17)
    at async Object.runCommand (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/@lhci/cli/src/upload/upload.js:581:16)

Done running autorun.
    at async run (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/@lhci/cli/src/cli.js:92:7)WARNING: upload command failed.
```

**Comment by noelmace** [comment]
The heroku "hobby" plan only allow 10000 records max in postgres DB.

So first, I deleted all entries before 2020-10-30:

```shell
$ heroku pg:psql       

lhci-fullwebdev::DATABASE=> SELECT COUNT(*) FROM runs;
 count 
-------
   846
(1 row)
lhci-fullwebdev::DATABASE=> DELETE FROM runs WHERE representative = false;
DELETE 564
lhci-fullwebdev::DATABASE=> \dt+
                            List of relations
 Schema |     Name      | Type  |     Owner      |  Size   | Description 
--------+---------------+-------+----------------+---------+-------------
 public | SequelizeMeta | table | ntaxpjqonycevy | 40 kB   | 
 public | builds        | table | ntaxpjqonycevy | 80 kB   | 
 public | projects      | table | ntaxpjqonycevy | 40 kB   | 
 public | runs          | table | ntaxpjqonycevy | 187 MB  | 
 public | statistics    | table | ntaxpjqonycevy | 2384 kB | 
(5 rows)

lhci-fullwebdev::DATABASE=> \d+ statistics
                                           Table "public.statistics"
  Column   |           Type           | Collation | Nullable | Default | Storage  | Stats target | Description 
-----------+--------------------------+-----------+----------+---------+----------+--------------+-------------
 id        | uuid                     |           | not null |         | plain    |              | 
 projectId | uuid                     |           |          |         | plain    |              | 
 buildId   | uuid                     |           |          |         | plain    |              | 
 url       | character varying(256)   |           |          |         | extended |              | 
 name      | character varying(100)   |           |          |         | extended |              | 
 value     | numeric(12,4)            |           |          |         | main     |              | 
 createdAt | timestamp with time zone |           |          |         | plain    |              | 
 updatedAt | timestamp with time zone |           |          |         | plain    |              | 
 version   | numeric(8,2)             |           |          |         | main     |              | 
Indexes:
    "statistics_pkey" PRIMARY KEY, btree (id)
Access method: heap

lhci-fullwebdev::DATABASE=> DELETE FROM statistics WHERE "updatedAt" < '2020-10-30'::date;
DELETE 5760
lhci-fullwebdev::DATABASE=> DELETE FROM runs WHERE "updatedAt" < '2020-10-30'::date;
DELETE 153
lhci-fullwebdev::DATABASE=> DELETE FROM builds WHERE "updatedAt" < '2020-10-30'::date;
DELETE 47
```

Then, I configured the server to automatically delete old builds using `deleteOldBuildsCron` (see https://github.com/fullwebdev/lhci-server-heroku/commit/af657f9cfb311670fced6b2df16a39b0f35289b7, https://github.com/GoogleChrome/lighthouse-ci/pull/471 & https://github.com/GoogleChrome/lighthouse-ci/pull/497) & tested it with https://github.com/fullwebdev/fullwebdev/actions/runs/415330920. We'll see if it's enough...
